### ISSUE TITLE
Release Date

### ISSUE THREAD

**Issue by drblaui** [fischer-hub/Shitwise#2]
I was wondering when the App will officially be released, because I really need it for personal reasons

**Comment by fischer-hub** [comment]
Hey @drblaui thanks for your interest on this project! 

As of right now Shitwise is only being developed by one person (me) and since I have quite some other tasks on my schedule there is not that much time available to put into Shitwise development. If you want to help push the development of this cool project in the future feel free to contribute to the code via PRs or support me with 1-3 million dollars so I can quit university and Lohnarbeit 🤗!

Best
G.C.
